### ISSUE TITLE
Rate limit remaining error

### ISSUE THREAD

**Issue by davidkane9** [sctyner/memer#3]
`> install_github("styner/memer")
Error: HTTP error 404.
  Not Found

  Rate limit remaining: 4998/5000
  Rate limit reset at: 2019-04-16 02:48:03 UTC

 
> `

[Perhaps this is relevant](https://github.com/forestgeo/learn/issues/148)?

**Comment by sctyner** [comment]
It was a typo! 

```r
library(devtools)
install_github("sctyner/memer")
```
