### ISSUE TITLE
Add meme_add() function

### ISSUE THREAD

**Issue by jayrobwilliams** [sctyner/memer#9]
Is there any interest in having a helper function to add memes to the `blankmemes.rda` file? I've written a simple one that I used to add the Yo Dawg meme in https://github.com/sctyner/memer/pull/8.
```
meme_add <- function(name, file) {
  
  cat('Make sure you have added the image file to the inst/extdata directory')
  
  blankmemes <- dplyr::add_row(blankmemes, filename = file, name = name) %>%
    dplyr::arrange(filename)
  
  usethis::use_data(blankmemes, overwrite = T)
  
}
```
Since `meme_get()` uses `memer::blankmemes` to load images and thus you have to recompile to get a new meme to work, it should probably stay hidden and just be a shortcut for contributors. I can open a PR if there's interest.

**Comment by sctyner** [comment]
Please add a PR! 😀 Thanks for the great idea.

**Comment by jayrobwilliams** [comment]
Done!
